// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Atmosphere struct {
	Temperature *Temperature `json:"temperature"`
	Pressure    *int         `json:"pressure,omitempty"`
	Humidity    *int         `json:"humidity,omitempty"`
}

type Conditions struct {
	Wind    *Wind `json:"wind"`
	Sunrise int   `json:"sunrise"`
	Sunset  int   `json:"sunset"`
}

type CurrentWeather struct {
	Weather    []*Weather  `json:"weather"`
	Atmosphere *Atmosphere `json:"atmosphere"`
	Conditions *Conditions `json:"conditions"`
}

type Temperature struct {
	Real      float64 `json:"real"`
	Min       float64 `json:"min"`
	Max       float64 `json:"max"`
	Feelslike float64 `json:"feelslike"`
}

type Weather struct {
	ID          int    `json:"id"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

type Wind struct {
	Speed  float64 `json:"speed"`
	Degree int     `json:"degree"`
	Gust   float64 `json:"gust"`
}
